### ISSUE TITLE
Enforce Linting on Commits and Pull Requests

### ISSUE THREAD

**Issue by marcel951** [schergen-org/JAWG#6]
## Description  
To maintain code quality and consistency, we need to enforce linting checks before commits and on pull requests. This can be achieved using a combination of **Husky** and **lint-staged** for local commits and **GitHub Actions** for CI validation.  

### 1. Set up Pre-Commit Hook  
- Install `husky` and `lint-staged`:  
  ```sh
  npm install husky lint-staged --save-dev
  ```  
- Initialize Husky:  
  ```sh
  npx husky install  
  ```  
- Add a pre-commit hook:  
  ```sh
  npx husky add .husky/pre-commit "npx lint-staged"  
  ```  
- Configure `lint-staged` in `package.json`:  
  ```json
  {
    "lint-staged": {
      "**/*.js": "eslint --fix"
    }
  }
  ```

### 2. Set up GitHub Action for Linting  
- Create a `.github/workflows/lint.yml` file with the following content:  
  ```yaml
  name: Lint Check

  on: [push, pull_request]

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm ci
        - run: npm run lint
  ```
- Ensure there is a `lint` script in `package.json`:  
  ```json
  {
    "scripts": {
      "lint": "eslint ."
    }
  }
  ```

## Acceptance Criteria  
- Commits should be blocked if they contain linting errors.  
- GitHub Actions should fail if a pull request does not meet linting standards.  
- The team should be notified of any failed linting checks in PRs.
